(* ::Package:: *)

PacletObject[
  <|
    "Name" -> "AntonAntonov/MonadicEventRecordsTransformations",
    "Description" -> "A software monad for transformation of event records",
    "Creator" -> "Anton Antonov",
    "License" -> "MIT",
    "PublisherID" -> "AntonAntonov",
    "Version" -> "1.0.0",
    "WolframVersion" -> "12.1+",
    "PrimaryContext" -> "AntonAntonov`MonadicEventRecordsTransformations`",
    "DocumentationURL" -> "https://resources.wolframcloud.com/PacletRepository/resources",
    "Extensions" -> {
      {
        "Kernel",
        "Root" -> "Kernel",
        "Context" -> {
          "AntonAntonov`MonadicEventRecordsTransformations`"
        },
        "Symbols" -> {
          "AntonAntonov`MonadicEventRecordsTransformations`$ERTMonFailure",
          "AntonAntonov`MonadicEventRecordsTransformations`EmptyComputationSpecificationRow",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMon",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonAddToContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonAggregateTimeSeries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonApplyTimeSeriesFunction",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonAssignContextTo",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonAssignTo",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonAssignValueTo",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonBind",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonComputeVariableStatistic",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonContexts",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropComputationSpecification",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropContingencyMatrices",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropEntityAttributes",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropEntityVariableRecordGroups",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropEventRecords",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropFromContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropNormalizationValues",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropTimeSeries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonDropVariableOutlierBoundaries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonEcho",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonEchoContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonEchoDataSummary",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonEchoFunctionContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonEchoFunctionValue",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonEchoValue",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonEntityVariableGroupsToTimeSeries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonFail",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonFindNormalizationValue",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonFindVariableOutlierBoundaries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonFold",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonGroupEntityVariableRecords",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonIf",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonIfElse",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonIterate",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonMakeContingencyMatrices",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonMakeContingencyMatrix",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonModifyContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonModule",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonNest",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonNestWhile",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonNormalize",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonOption",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonProcessComputationSpecification",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonPutContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonPutValue",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonReadData",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonRemapEntitiesByGroups",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonRetrieveFromContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetComputationSpecification",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetContingencyMatrices",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetEntityAttributes",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetEntityVariableRecordGroups",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetEventRecords",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetNormalizationValues",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetTimeSeries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetValue",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSetVariableOutlierBoundaries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonSucceed",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeComputationSpecification",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeContext",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeContingencyMatrices",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeContingencyMatrix",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeEntityAttributes",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeEntityVariableRecordGroups",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeEventRecords",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeNormalizationValues",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeTimeSeries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeValue",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonTakeVariableOutlierBoundaries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonToTimeSeries",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonUnit",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonUnitQ",
          "AntonAntonov`MonadicEventRecordsTransformations`ERTMonWhen",
          "AntonAntonov`MonadicEventRecordsTransformations`ProcessComputationSpecification",
          "AntonAntonov`MonadicEventRecordsTransformations`WeatherEventRecords"
        }
      },
      {
        "Documentation",
        "Root" -> "Documentation",
        "Language" -> "English"
      }
    }
  |>
]
